### PR TITLE
clear_buffer_region doesn't need cs switching

### PR DESCRIPTION
**Pull request by mbuesch**
It doesn't access the hardware.

### CODE REVIEW

**Review by wjakobczyk — APPROVED** [review]

**Comment by mbuesch** [comment]
rebased.

**Comment by mbuesch** [comment]
What do you think? Is this ready for pulling, or do we need some changes?
Thanks for your support.

**Comment by mbuesch** [comment]
Bump.
Do you want to pull this?

Thanks :)

**Comment by wjakobczyk** [comment]
Is the delay param still needed? I guess not, how about removing it?

**Comment by mbuesch** [comment]
Yes, the delay parameter is not needed anymore.
I didn't remove it to keep the interface compatible. Just to make it possible to have another api compatible release with this change applied.

But I think it can be removed together the next api breaking change.
I do actually have such an api breaking change in my submission pipeline (update to embedded-hal 1).
So I can remove the parameter then together with that change.

**Pull request merged**
