### PR TITLE
Update to embedded-hal v1 and more

### PR DESCRIPTION
**Pull request by mbuesch**
Hi,

in this PR the changes are:

- Update to embedded-hal 1. This brings us to the current major stable version of embedded-hal.
- Update embedded-graphics to 0.8.
- Update num-derive to 0.4.
- Removal of unneeded delay parameters from all functions. This is an API breaking change.
- Version number bump.

This code has been tested on an ESP32 with esp-idf-hal git plus a patch to fix a bug in esp-idf-hal (https://github.com/esp-rs/esp-idf-hal/pull/367). There's no released version with embedded-hal 1, yet. 

I did not test it on STM32 and I did not check the example, because I don't have an STM32.

My plan is to also add an ESP32 example to the tree, but I'm currently unsure how to do that best. The cargo config would probably clash.

What do you think?

### CODE REVIEW

**Comment by wjakobczyk** [comment]
Current example does not even build, so try to fix this first. Then I can see if I can dig out the old hardware and run it.
Maybe a clever use of feature flags will make it possible to include examples for both platforms? I don't have experience with multi-target projects TBH...

**Comment by mbuesch** [comment]
Thanks for the comment.
Yes, I think I should probably setup a build environment to at least build test the example.

**Comment by mbuesch** [comment]
Do you have a link to some documentation about how to set up a build environment for the example?

**Comment by wjakobczyk** [comment]
> Do you have a link to some documentation about how to set up a build environment for the example?

You don't need any special setup, just Rust with target.

**Comment by mbuesch** [comment]
Cool. Thanks. I'll take a look to make the example compile again.

**Comment by mbuesch** [comment]
I have fixed the STM32 example build.
From my perspective this PR would now be ready for pull.

**Comment by wjakobczyk** [comment]
Thanks, I've got it up and running on my old STM32F4 board.

**Comment by wjakobczyk** [comment]
I have published this as v.0.4.0 on crates.io

**Comment by mbuesch** [comment]
Thanks for your help :)

**Pull request merged**
